### ISSUE TITLE
"View in P4V" does not work

### ISSUE THREAD

**Issue by JoshHarmon** [perforce/P4VS#15]
P4VS 2023.2.256.2238
Rev. P4V/NTX64/2024.1/2573667

![image](https://github.com/perforce/P4VS/assets/2958794/1b1389ef-8970-427e-8c1a-19c88b7d1a4d)

![image](https://github.com/perforce/P4VS/assets/2958794/7841afc2-1b5d-4755-aa2f-443ad783b406)

**Comment by p4chirag** [comment]
Hi @JoshHarmon,
Thank you for raising this issue.
-s option is deprecated in recent release of P4V 2024.1 due to which p4v is not launched.
The issue has already been prioritized for resolution in the upcoming release. As a workaround, you can use an earlier version of P4V.

Please note that issues are not be managed on GitHub. All issues should be recorded via Perforce's standard support process (https://www.perforce.com/support/request-support).
